GET http://localhost:3000/users

###

GET http://localhost:3000/users?order=oldest&offset=2&limit=1

###

GET http://localhost:3000/users/3651f3f4-1c0d-4067-83ba-e86de21

###
# 기존 POST 
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "kimdsdfsdfsdfaily15@naver.com",
    "firstName": "daily",
    "lastName": "kim",
    "address": "seoul in korea"
}


###

# UserPreferente 반영 한 POST 구조

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "kimda123ily11265@naver.com",
    "firstName": "daily",
    "lastName": "kim",
    "address": "seoul in korea",
    "userPreference" : {
        "receiveEmail" : true
    }
}

###

POST http://localhost:3000/users/0917464a-4241-48a7-b563-52eb28464c77/save
Content-Type: application/json

{
    "productId": "10f12b65-20f5-43d9-860e-faf4890e2a9e"
}


###

PATCH http://localhost:3000/users/7e60e8a0-8130-4d62-b604-6fe953ecfbbe
Content-Type: application/json

{
    "firstName": "daily123"
}



###

DELETE http://localhost:3000/users/7e60e8a0-8130-4d62-b604-6fe953e
# userPreference 를 가지고 있는 user id를 선택하여 확실히 지워지는지 확인 