GET http://localhost:3000/users

###

GET http://localhost:3000/users?order=oldest&offset=2&limit=1

###

GET http://localhost:3000/users/3651f3f4-1c0d-4067-83ba-e86de2143024

###
# 기존 POST 
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "kimdaily15@naver.com",
    "firstName": "daily",
    "lastName": "kim",
    "address": "seoul in korea"
}


###

# UserPreferente 반영 한 POST 구조

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "kimda123ily11265@naver.com",
    "firstName": "daily",
    "lastName": "kim",
    "address": "seoul in korea",
    "userPreference" : {
        "receiveEmail" : true
    }
}



###

PATCH http://localhost:3000/users/3651f3f4-1c0d-4067-83ba-e86de2143024
Content-Type: application/json

{
    "firstName": "daily"
}


###

DELETE http://localhost:3000/users/1d5s1a3fd5-d1a5d1f